# Plugin creado por: @Piratemajo
# Configuracion del plugin
# Opcion del contador de tiempo
timer: 10
rounds: 2
explosion:
  radius: 4.0

messages:
  time_remaining: "Tiempo restante: "
  tnt_holder: "{player} tiene la TNT."
  player_exploded: "{player} ha explotado."
  game_winner: "{player} ha ganado el juego."
  game_over: "El juego ha terminado."
  tnt_passed: "{player1} ha pasado la TNT a {player2}."
  round_winner: "{player} ha ganado la ronda."
  round_over: "La ronda ha terminado."

music:
  enabled: true
  tracks:
    - "minecraft:music_disc.cat"
    - "minecraft:music_disc.chirp"
  external_url: "https://example.com/music.mp3"