name: Tntemu
version: '1.1-Beta'
main: es.tntemu.Tntemu
api-version: '1.21'
authors: [SrJavier]
commands:
  tntemu:
    description: Comienza o detiene el juego TNTEmu.
    usage: /tntemu <start|stop|setup|select|list>
    aliases: [tnt]
    permission: tntemu.use
    permission-message: No tienes permisos para usar este comando.
    tab-complete: /tntemu <start|stop|setup|select|list>
    tab-complete: /tntemu start <arena>
    tab-complete: /tntemu stop <arena>
    tab-complete: /tntemu setup <arena>
    tab-complete: /tntemu select <arena>
    tab-complete: /tntemu list
    tab-complete: /tntemu list <arenas>
    tab-complete: /tntemu list <players>
    tab-complete: /tntemu list <all>
    tab-complete: /tntemu list <all> <arenas>
    tab-complete: /tntemu list <all> <players>